In [3]:
print("Hello!!")

Hello!!


In [5]:
print("My Name is Vishnu!!")

My Name is Vishnu!!


In [1]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [2]:
arr2 = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(arr2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(4)


array([0., 0., 0., 0.])

In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

# Linspace: np.linspace(a,b,c)  prints array of c evenly spaced points between a and b

In [13]:
np.linspace(0,10,20)  #prints 20 evenly spaced points between 0 and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
np.eye(4)    #to create identical matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)   ##pass 1 args for 1d matrix , 2 args for 2d matrix 
                    # and elements will be randomly from 0-1 range

array([0.42450763, 0.93607714, 0.25992759, 0.36226104, 0.72158931])

In [18]:
np.random.randn(3)

array([ 2.47030942, -0.72868146,  0.49382741])

In [22]:
arr = np.random.randint(1,50,10)   #if u don't specify 3rd arg ,then by default it will be 1.

In [23]:
arr

array([ 7, 15,  6, 30, 49, 27, 43, 11, 11, 37])

In [29]:
arr.reshape(2,5)      

array([[ 7, 15,  6, 30, 49],
       [27, 43, 11, 11, 37]])

In [32]:
arr.max()

49

In [33]:
arr.min()

6

In [34]:
arr.argmax()  #returns the index of max value , same for min 

4

In [35]:
arr= arr.reshape(5,2)

In [37]:
arr.shape

(5, 2)

In [39]:
arr.dtype      #returns the datatype of elements in array

dtype('int64')