In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
slice_of_arr= arr[0:5]

In [29]:
slice_of_arr

array([100, 100, 100, 100, 100])

# Brodcasting of numpy array

In [6]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
copy_of_arr = arr.copy()
copy_of_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
copy_of_arr[:]= 99
copy_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Indexing and slicing of 2d array

In [11]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr_2d[1,1]     # OR arr_2d[1][1]

5

In [15]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [16]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [17]:
arr_2d[1:2,1:2]

array([[5]])

In [18]:
arr_2d[1:2]

array([[4, 5, 6]])

In [19]:
arr_2d[,1:2]

SyntaxError: invalid syntax (1463031708.py, line 1)

In [20]:
arr_2d[:,1:2]

array([[2],
       [5],
       [8]])

# Condition Silicing

In [25]:
arr = np.arange(10)

In [26]:
arr[arr>6]

array([7, 8, 9])

In [27]:
arr[arr<=3]

array([0, 1, 2, 3])