In [3]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr + arr      #Also works for - , * , /

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
arr/arr

/tmp/ipykernel_82417/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [5]:
arr*10       #Also works for - , + , /

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
arr/0

/tmp/ipykernel_82417/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
/tmp/ipykernel_82417/4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [10]:
6/arr

/tmp/ipykernel_82417/3243852102.py:1: RuntimeWarning: divide by zero encountered in true_divide
  6/arr


array([       inf, 6.        , 3.        , 2.        , 1.5       ,
       1.2       , 1.        , 0.85714286, 0.75      , 0.66666667,
       0.6       ])

## Exponents

In [11]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Other operations

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
np.log(arr)

/tmp/ipykernel_82417/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])